#!/usr/bin/env bash
diff <(./index.js <<EOF
schema {
  query: Query
}

type Query {
  foo: Foo
  bar: Bar
  baz: String
}

type Foo {
  someField: Int
  otherField: String
}

type Bar {
  yay: Boolean
  ok: Boolean
}
EOF) <(cat <<EOF
// This file was auto-generated by fragment-codegen. Do not edit it by hand.

export const Foo = \`fragment Foo on Foo {
  someField
  otherField
}
\`

export const Bar = \`fragment Bar on Bar {
  yay
  ok
}
\`
EOF) && exit 0 || exit 1
