#!/usr/bin/env bash
diff <(./index.js <<EOF
schema {
  query: Query
}

type Query {
  foo: Foo
  bar: Bar
  ignoreStuffWithArgs(becauseWeDunnoWhatTheyAre: Boolean): ID
}

type Foo {
  scalar: Int
  object: Bar
  scalarList: [Int]
  objectList: [Bar]
}

type Bar {
  yay: Boolean
  ok: Boolean
}
EOF) <(cat <<EOF
// This file was auto-generated by graphql-fragment-codegen. Do not edit it by hand.

export const Foo = \`fragment Foo on Foo {
  scalar
  object {
    yay
    ok
  }
  scalarList
  objectList {
    yay
    ok
  }
}
\`

export const Bar = \`fragment Bar on Bar {
  yay
  ok
}
\`
EOF) && exit 0 || exit 1
